services:
  - type: web
    name: rsshub
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
